# Generated by Django 3.0 on 2025-07-31 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=30)),
                ('rating', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=500)),
                ('place', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('REGISTRATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Registration')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Cp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='CP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Cp'),
        ),
    ]
