# Generated by Django 3.0 on 2025-07-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cp',
            name='photo',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cp',
            name='proof',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cp',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cp',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
