# Generated by Django 3.0 on 2025-08-23 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20250810_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='review',
        ),
    ]
