# Generated by Django 3.0 on 2025-09-02 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_join_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='USER',
        ),
        migrations.AddField(
            model_name='review',
            name='REGISTRATION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Registration'),
        ),
    ]
