# Generated by Django 3.0 on 2025-09-02 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20250902_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='REGISTRATION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Registration'),
        ),
    ]
