# Generated by Django 3.0 on 2025-09-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='cp',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
