# Generated by Django 3.0 on 2025-09-30 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_cp_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=30)),
                ('rating', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Course')),
                ('REGISTRATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Registration')),
            ],
        ),
    ]
