# Generated by Django 3.0 on 2025-11-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_creview'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transcribedtext',
            field=models.TextField(default=1, max_length=65535),
            preserve_default=False,
        ),
    ]
