# Generated by Django 3.0 on 2026-01-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='state',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
